version: "3.9"
services:
  client:
    build: client
    ports:
      - "3000:3000"
  envoy:
    build: envoy
    ports:
      - "3333:3333"
      - "9901:9901"
  server:
    build: server
    ports:
      - "8000:8000"
