// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: model/snowcast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_snowcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_snowcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_model_snowcast_proto_rawDescGZIP(), []int{0}
}

type WelcomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Songs []string `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
}

func (x *WelcomeReply) Reset() {
	*x = WelcomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_snowcast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeReply) ProtoMessage() {}

func (x *WelcomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_snowcast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeReply.ProtoReflect.Descriptor instead.
func (*WelcomeReply) Descriptor() ([]byte, []int) {
	return file_model_snowcast_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeReply) GetSongs() []string {
	if x != nil {
		return x.Songs
	}
	return nil
}

type PlaySongRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Song string `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
}

func (x *PlaySongRequest) Reset() {
	*x = PlaySongRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_snowcast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaySongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySongRequest) ProtoMessage() {}

func (x *PlaySongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_snowcast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySongRequest.ProtoReflect.Descriptor instead.
func (*PlaySongRequest) Descriptor() ([]byte, []int) {
	return file_model_snowcast_proto_rawDescGZIP(), []int{2}
}

func (x *PlaySongRequest) GetSong() string {
	if x != nil {
		return x.Song
	}
	return ""
}

type PlaySongReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PlaySongReply) Reset() {
	*x = PlaySongReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_snowcast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaySongReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySongReply) ProtoMessage() {}

func (x *PlaySongReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_snowcast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySongReply.ProtoReflect.Descriptor instead.
func (*PlaySongReply) Descriptor() ([]byte, []int) {
	return file_model_snowcast_proto_rawDescGZIP(), []int{3}
}

func (x *PlaySongReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_model_snowcast_proto protoreflect.FileDescriptor

var file_model_snowcast_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x6e, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x6e, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x74,
	0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x24, 0x0a, 0x0c, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x22, 0x23, 0x0a,
	0x0d, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x8c, 0x01, 0x0a, 0x08, 0x53, 0x6e, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x74, 0x12,
	0x3c, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x16, 0x2e, 0x73, 0x6e,
	0x6f, 0x77, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x57,
	0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x73, 0x6e, 0x6f, 0x77,
	0x63, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x74, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x0b, 0x5a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_snowcast_proto_rawDescOnce sync.Once
	file_model_snowcast_proto_rawDescData = file_model_snowcast_proto_rawDesc
)

func file_model_snowcast_proto_rawDescGZIP() []byte {
	file_model_snowcast_proto_rawDescOnce.Do(func() {
		file_model_snowcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_snowcast_proto_rawDescData)
	})
	return file_model_snowcast_proto_rawDescData
}

var file_model_snowcast_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_snowcast_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),    // 0: snowcast.HelloRequest
	(*WelcomeReply)(nil),    // 1: snowcast.WelcomeReply
	(*PlaySongRequest)(nil), // 2: snowcast.PlaySongRequest
	(*PlaySongReply)(nil),   // 3: snowcast.PlaySongReply
}
var file_model_snowcast_proto_depIdxs = []int32{
	0, // 0: snowcast.Snowcast.SayHello:input_type -> snowcast.HelloRequest
	2, // 1: snowcast.Snowcast.PlaySong:input_type -> snowcast.PlaySongRequest
	1, // 2: snowcast.Snowcast.SayHello:output_type -> snowcast.WelcomeReply
	3, // 3: snowcast.Snowcast.PlaySong:output_type -> snowcast.PlaySongReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_snowcast_proto_init() }
func file_model_snowcast_proto_init() {
	if File_model_snowcast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_snowcast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_snowcast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_snowcast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaySongRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_snowcast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaySongReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_snowcast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_snowcast_proto_goTypes,
		DependencyIndexes: file_model_snowcast_proto_depIdxs,
		MessageInfos:      file_model_snowcast_proto_msgTypes,
	}.Build()
	File_model_snowcast_proto = out.File
	file_model_snowcast_proto_rawDesc = nil
	file_model_snowcast_proto_goTypes = nil
	file_model_snowcast_proto_depIdxs = nil
}
