// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SnowcastClient is the client API for Snowcast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowcastClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Snowcast_SayHelloClient, error)
	BroadcastMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type snowcastClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowcastClient(cc grpc.ClientConnInterface) SnowcastClient {
	return &snowcastClient{cc}
}

func (c *snowcastClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Snowcast_SayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Snowcast_ServiceDesc.Streams[0], "/snowcast.Snowcast/SayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &snowcastSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Snowcast_SayHelloClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type snowcastSayHelloClient struct {
	grpc.ClientStream
}

func (x *snowcastSayHelloClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snowcastClient) BroadcastMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/snowcast.Snowcast/BroadcastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowcastServer is the server API for Snowcast service.
// All implementations must embed UnimplementedSnowcastServer
// for forward compatibility
type SnowcastServer interface {
	SayHello(*HelloRequest, Snowcast_SayHelloServer) error
	BroadcastMessage(context.Context, *Message) (*emptypb.Empty, error)
	mustEmbedUnimplementedSnowcastServer()
}

// UnimplementedSnowcastServer must be embedded to have forward compatible implementations.
type UnimplementedSnowcastServer struct {
}

func (UnimplementedSnowcastServer) SayHello(*HelloRequest, Snowcast_SayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSnowcastServer) BroadcastMessage(context.Context, *Message) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessage not implemented")
}
func (UnimplementedSnowcastServer) mustEmbedUnimplementedSnowcastServer() {}

// UnsafeSnowcastServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowcastServer will
// result in compilation errors.
type UnsafeSnowcastServer interface {
	mustEmbedUnimplementedSnowcastServer()
}

func RegisterSnowcastServer(s grpc.ServiceRegistrar, srv SnowcastServer) {
	s.RegisterService(&Snowcast_ServiceDesc, srv)
}

func _Snowcast_SayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnowcastServer).SayHello(m, &snowcastSayHelloServer{stream})
}

type Snowcast_SayHelloServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type snowcastSayHelloServer struct {
	grpc.ServerStream
}

func (x *snowcastSayHelloServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Snowcast_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowcastServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowcast.Snowcast/BroadcastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowcastServer).BroadcastMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// Snowcast_ServiceDesc is the grpc.ServiceDesc for Snowcast service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Snowcast_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowcast.Snowcast",
	HandlerType: (*SnowcastServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastMessage",
			Handler:    _Snowcast_BroadcastMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello",
			Handler:       _Snowcast_SayHello_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "model/snowcast.proto",
}
